<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Rent Me! '. $this->translate('Home'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/prova.jpg', 'href' => $this->basePath() . '/img/prova.jpg'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/skel-noscript.css'))
        ->prependStylesheet($this->basePath('css/fontface.css'))
        ->prependStylesheet($this->basePath('css/style-wide.css'))?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/init.js'))
        ->prependFile($this->basePath('js/chat.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/skel.min.js'))
        ->prependFile($this->basePath('js/skel-panels-min.js'))?>

</head>
<body>
<div id="header" class="skel-panels-fixed">
    <div class="top">
        <div id="logo"> <span class="image avatar48"><img src="img/prova.jpg" alt=""></span>
            <h1 id="title">Nome Utente</h1>
            <span class="byline">Ranking ee</span> </div>
        <nav id="nav">
            <ul>
                <li><a href="#top" id="top-link" class="skel-panels-ignoreHref"><span class="icon icon-home">News</span></a></li>
                <li><a href="#portfolio" id="portfolio-link" class="skel-panels-ignoreHref"><span class="icon icon-th">Impostazioni</span></a></li>
                <li><a href="#about" id="about-link" class="skel-panels-ignoreHref"><span class="icon icon-user">Gruppi</span></a></li>
                <li><a href="#contact" id="contact-link" class="skel-panels-ignoreHref"><span class="icon icon-envelope">Messaggi</span></a></li>
            </ul>
        </nav>
    </div>
    <div class="bottom">
        <ul class="icons">
            <li><a href="#" class="icon icon-twitter"><span>Twitter</span></a></li>
            <li><a href="#" class="icon icon-facebook"><span>Facebook</span></a></li>
            <li><a href="#" class="icon icon-github"><span>Github</span></a></li>
            <li><a href="#" class="icon icon-dribbble"><span>Dribbble</span></a></li>
            <li><a href="#" class="icon icon-envelope"><span>Email</span></a></li>
        </ul>
    </div>
</div>
<button class="icon icon-user" id="chat"></button>

<div id="areaChat" align="center"><br/>
    <input type="search" placeholder="cerca" />
</div>

<?php echo $this->content; ?>



<div id="footer">
    <div class="copyright">
        <p>&copy; 2045 Jane Doe. All rights reserved.</p>
        <ul class="menu">
            <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</div>
            <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
