<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
       <?php echo $this->headTitle('Rent Me! '. $this->translate('Login'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/prova.jpg', 'href' => $this->basePath() . '/img/prova.jpg'))
                        ->prependStylesheet($this->basePath('css/login.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/login.js')); ?>

    </head>
    <body>
        <div class="cont">
            <div class="demo">
                <div class="login">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
            <footer>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
