<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<div>
    <div align="center" class="row">
        <div class="col-sm-2"><h1>logo(cercalo te uu)</h1></div>
        <div class="col-sm-10"><h1> titolo(rent me - nome proposto da lat)</h1></div>
    </div><br/><hr>

    <div class="row">
        <div class="col-sm-4">
            <div align="center">
                 <h3>Login</h3>
                <p>Accedi al tuo account</p>
                <br/>
            </div>

            <div class="row">
                <div class="col-sm-6"><p>Email:</p></div>
                <div class="col-sm-6"><p>Password:</p></div>
            </div>

            <div class="row">
                <div class="col-sm-6"> <input type="text" name="login" placeholder="Email" class="form-control"></div>
                <div class="col-sm-6"> <input type="password" name="login" placeholder="Password" class="form-control"></div>
            </div>
        </div>

        <div class="col-sm-4"></div>

        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-4">
                     <div align="right">
                         <h3>Sign up</h3>
                    </div>
                 </div>
            </div><br/>

                <div class="row">
                    <div class="col-sm-6"><input type="text" name="signIn" placeholder="First Name" class="form-control"> </div>
                    <div class="col-sm-6"><input type="text" name="signIn" placeholder="Last Name" class="form-control"> </div>
                </div><br/>
                <div class="row">
                    <div class="col-sm-6"><input type="text" name="signIn" placeholder="Email" class="form-control"></div>
                    <div class="col-sm-6"><input type="text" name="signIn" placeholder="Confirm Email" class="form-control"></div>
                </div><br/>
                <div class="row">
                    <div class="col-sm-6"><input type="password" name="signIn" placeholder="Password" class="form-control"></div>
                    <div class="col-sm-6"><input type="password" name="signIn" placeholder="Confirm Password" class="form-control"></div>
                </div><br/>
                <div class="row">
                    <div class="col-sm-4"><input type="text" name="signIn" placeholder="Day" class="form-control"></div>
                    <div class="col-sm-4"><input type="text" name="signIn" placeholder="Month" class="form-control"></div>
                    <div class="col-sm-4"><input type="text" name="signIn" placeholder="Year" class="form-control"></div>
                </div><br/>
                    <div class="col-md-12"><input type="checkbox" name="signIn"> I have read and agree to the <a href="url">Terms of Use</a> and <a href="url">Privacy Policy</a>.</div>
                    <br/>
                    <div id="btn"><button type="button" class="btn btn-info btn-lg btn-block">Sign up</button></div>

                </div>
            </div>
        </div>
    </div>
</div>


