<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<div>
    <div class="row">
        <div class="col-sm-3"><h2>Rent Me!</h2></div>
        <div class="col-sm-6"><input type="search"></div>
        <div class="col-sm-3"><input type="button" value="Profilo"></div>
    </div><br/><hr/>

    <div class="row">
        <div class="col-sm-2">
            <!-- foto, -->
        </div>

    </div>

    <footer>
        <div class="row">
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
        </div>
    </footer>
</div>