
<div align="center">
    <section>

        <header class="clearfix">
            <div class="liks">
                <i class="icon"></i>
                <span>255</span>
            </div>
            <div class="user">
                <div class="avatar">
                    <img alt="Dwayne Johnson" src="http://i.imgur.com/DmPjhGo.jpg">
                </div>
                <h2>User</h2>
                <p>lvl</p>
                <a href="#" class="follow"><span>+</span>Chiedi Amicizia</a>
            </div>

            <div class = "hl">
                <ul class="menu">
                    <a href="#" class="active profile">Profile</a>
                    <a href="#" class="timeline">Timeline</a>
                    <a href="#" class="podcast">Podcast</a>
                </ul>
            </div>

        </header>




    </section>
</div>
