<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<div>
    <div class="row">
        <div class="col-sm-3"><h2>Rent Me!</h2></div>
        <div class="col-sm-6"><input type="search"></div>
        <div class="col-sm-3"><input type="button" value="Profilo" onclick = "location='profilo'"></div>
    </div><br/><hr/>

    <div class="row">
        <div class="col-sm-2">
            <img src="<?php echo $this->basePath('img/provaprofilo.jpg') ?>" alt="Profilo" style="width:200px;height:200px;"></image>
        </div>

    </div>

    <footer>
        <div class="row">
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div> 
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
            <div class="col-sm-2"><a>Impostazioni</a></div>
        </div>
    </footer>
</div>