<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<style>
    #gruppo{
        border-right: solid lightsteelblue 1px;
    }

    #chat{
        border-left: solid lightsteelblue 1px;
        border-top: solid lightsteelblue 1px;
    }
</style>
<div>
    <div class="row">
        <div class="col-sm-3"><h2>Rent Me!</h2></div>
        <div class="col-sm-6"><input type="search"></div>
        <div class="col-sm-3"><input type="button" value="Profilo" onclick = "location='profilo'"></div>
    </div><br/>

    <div class="row">
        <div class="col-sm-3" id="gruppo">
            <h5>Gruppi</h5>
        </div>

        <div class="col-sm-6">
            <h5>NEWS!</h5>
        </div>

        <div class="col-sm-3" id="chat">
            <h5>CHAT</h5>
        </div>

        <div><br/><hr/>
            <footer>
                <div class="row">
                    <div class="col-sm-2"><a>Impostazioni</a></div>
                    <div class="col-sm-2"><a>Impostazioni</a></div>
                    <div class="col-sm-2"><a>Impostazioni</a></div>
                    <div class="col-sm-2"><a>Impostazioni</a></div>
                    <div class="col-sm-2"><a>Impostazioni</a></div>
                    <div class="col-sm-2"><a>Impostazioni</a></div>
                </div>
            </footer>
        </div>
    </div>

</div>
